### ISSUE TITLE
Installing googleanalytics plugin returns "BackendUnavailable" error

### ISSUE THREAD

**Issue by michael-long88** [ckan/ckanext-googleanalytics#51]
From everything I can tell, it looks like this error typically revolves around compatibility issues with python2 and python3. I'm running ckan 2.8, which should be compatible.

```
pip install -e  git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining ckanext-googleanalytics from git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics
  Updating /usr/lib/ckan/venv/src/ckanext-googleanalytics clone
  Running command git fetch -q --tags
  Running command git reset --hard -q cbee3f06d6374492e12c204af7ef1ddd3ed00a4a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 300, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 532, in prepare_editable_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 161, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable
```

**Comment by smotornyuk** [comment]
Can you share your versions of `pip` and `setuptools`?

**Comment by michael-long88** [comment]
pip 20.1.1
setuptools 36.1.0

**Comment by guibos** [comment]
I have the same issue. I upgraded setuptools, and succesfully installed package, but I need to test.

**Comment by Conzar** [comment]
I am also having this issue on CKAN 2.8.
