### ISSUE TITLE
pip install failed to build wheel

### ISSUE THREAD

**Issue by ac-small** [ckan/ckanext-googleanalytics#64]
I ran the command to install the extension:
pip install -e  git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics

And I am getting the following error:

Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /app/ckan/venv/bin/python /app/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpDHg8Cg
       cwd: /app/ckan/venv/src/ckanext-googleanalytics
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/app/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/app/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/app/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/app/ckan/venv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/app/ckan/venv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/app/ckan/venv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/app/ckan/venv/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 16, in <module>
      with open(os.path.join(HERE, 'README.md'), encoding='utf-8') as f:
  TypeError: 'encoding' is an invalid keyword argument for this function
  ----------------------------------------
ERROR: Command errored out with exit status 1: /app/ckan/venv/bin/python /app/ckan/venv/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpDHg8Cg Check the logs for full command output.

**Comment by Nenad-N** [comment]
Is there any answer, regarding this question?

**Comment by smotornyuk** [comment]
Must be fixed now
